# Generated by Django 4.2.1 on 2023-06-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['title'], 'verbose_name': 'женщины', 'verbose_name_plural': 'женщиныыыы'},
        ),
    ]
